Dataset:
  train_data_path: "C://Machine Learning//Datasets//TrafficSigns//train_data.json"
  val_data_path: "C://Machine Learning//Datasets//TrafficSigns//val_data.json"
  classes_path: "C://Machine Learning//Datasets//TrafficSigns//classes.txt"
  num_classes: 43
Train:
  learning_rate: 0.001
  lr_scheduler: "StepDecay"  # Not implemented
  batch_size: 2
  epochs: 20
  image_size: [240, 160]
  channels: 3
  optimizer: "adam"
  arch: "ResNet50"
  pretrained: False  # Not implemented
  device: 0
Augmentation:
  RandomCrop:  # Implement crop with the same size
    p: 0.0
  RandomHorizontalFlip:
    p: 0.25
  RandomRotate:
    p: 0.25
    angle: 30
  RandomBrightness:
    p: 0.2
    low_value: 0.5
    high_value: 4.0
  RandomZoom:  # Not implemented
    p: 0.0

Logging:
  tb_logdir: "C:\\Machine Learning\\Classification Networks PyTorch\\logs\\TrafficSigns"
  ckpt_dir: "C:\\Machine Learning\\Classification Networks PyTorch\\checkpoints\\TrafficSigns\\ResNet50_1"
