Dataset:
  train_data_path: "C://Machine Learning//Datasets//flowers_102//train_data.json"
  val_data_path: "C://Machine Learning//Datasets//flowers_102//val_data.json"
  classes_path: "C://Machine Learning//Datasets//flowers_102//class_inds.txt"
  num_classes: 102
Train:
  lr_scheduler:
    lr_init: 0.01
    lr_end: 0.0001
    StepDecay:
      use: True
      epoch_steps: [1, 3, 5]
  batch_size: 1
  epochs: 20
  eval_per_epoch: 3
  image_size: [416, 416]  # divisible by 32
  channels: 3
  optimizer: "adam"
  arch: "ResNet34"
  pretrained: ""
  device: 0
Augmentation:
  RandomCrop:  # Implement crop with the same size
    p: 0.0
  RandomHorizontalFlip:
    p: 0.25
  RandomRotate:
    p: 0.25
    angle: 30
  RandomBrightness:
    p: 0.2
    low_value: 0.5
    high_value: 4.0

Logging:
  tb_logdir: "C:\\Machine Learning\\Classification Networks PyTorch\\logs\\flowers_102"
  ckpt_dir: "C:\\Machine Learning\\Classification Networks PyTorch\\checkpoints\\flowers_102\\ResNet34_1"
